### ISSUE TITLE
Add instant input validation on authentication forms

### ISSUE THREAD

**Issue by paarals** [openpoke/decidim#4]
**Is your feature request related to a problem? Please describe.**
Users need to send the form in order to see if they made a mistake. Here are some pain points that were raised in user interview.

    Reloading the page each time which makes the user
    start form the top which feels like doing it all over again as the user has to scroll to see the error messages
    retype the password twice
    Error messages are not always easy to understand
    Users who made multiple errors feel overwhelmed by all the red field and error message

**Describe the solution you'd like**
Use instant input validation on the form so we can dynamically show the user errors as she is typing (without having to send the form and scroll the whole thing) so she can correct herself one error at a time.

The fields that are subject to this feature are :

    Nickname 
    As a user who is typing her nickname I get an error if I add a space or a special special character

    Password
    As a user who is typing her password I can see password conditions turn green as I go. (Here is a good example (External link) (External link) 
    (Enllaç extern), if you start typing a password you'll see a tooltip. This is related to this Meta proposal (External link) (External link) 
    (Enllaç extern))
    Email
    As a user who type an email I get an error if I input a space or a special character that cannot be used in an email adress [any other condition ?)

**Describe alternatives you've considered**
No

**Additional context**
This proposal is part of a larger scope to improve authentication flow in Decidim. Working document here 
(Enllaç extern).

**Does this issue could impact on users private data?**
No

**Funded by**
OSP and Angers

**Comment by simonaszilinskas** [comment]
New suggested texts:

Password errors:

is too similar to your nickname → The password you entered is too similar to your nickname. For security reasons, please choose a unique password.
doesn’t match password (irrelevant if there will only be one password field)
is too short → The password you entered is too short. For security reasons, please choose a password of 10 characters or more.
Nickname errors:

is invalid → the nickname you entered is invalid because: {reason}

{reasons}:

it contains a space. You can switch out the space for ‘-’ or ‘_’
it contains characters that are unsupported. Please only use letters, numbers or ‘-’ and ‘_’
it is too long. Please choose a shorter nickname.
Email errors:

has already been taken → The email you have entered is already used by another account. Please use another email or sign in if you already have an account.
There’s an error in this field → The email you have entered is not in a valid form. Please check for typos.

**Comment by microstudi** [comment]
This is already testeable in https://decidim-signup.dev.pokecode.net/users/sign_up

**Comment by microstudi** [comment]
Note that the nickname is not being validated, this is because it will be removed in the next PR and generated automatically from the name or email

**Comment by virgile-dev** [comment]
Hey @microstudi (ping @simonaszilinskas)
Just demoed this to a colleague. Right now the validation is done everytime I press a key which is a bit annoying.
Can we do a check and display the error when the user changes its focus to another field ?

**Comment by microstudi** [comment]
@virgile-dev I have a question relating this. Do you want the validation only when the focus on a field is lost, that's ok, but the built-in (already existing in Decidim) validation still does the same thing (although it only checks simpler things).
This is how it looks by default (no instant validation applied):


![Image](https://user-images.githubusercontent.com/1401520/178756223-4277d164-472c-4a02-9559-91549e65c478.png)

May it be that what is bothering you is the movement of the page happening because the error class is being removed and put back in again? This can be easily solved.
